### ISSUE TITLE
OMG I LOVE U! :)

### ISSUE THREAD

**Issue by jfrux** [justintime/ST-Monoprice-Dual-Relay-Module#1]
Now I just can't wait until monoprice restocks these so I can try it.
This sounds like a miracle for expanding z-wave houses on the cheap for real.

Just can't justify spending $1000 dollars to replace all the switches in my house.

**Comment by jfrux** [comment]
I know it's not really a big help... but just updated the link in the readme to the new raw groovy file instead of the previous location.  But it's least I can do :p

**Comment by justintime** [comment]
The device type works well, but I think I'll eventually replace these with z-wave switches.  The OCD in me has such a hard time with the switch being out of sync with the light :)

**Comment by jfrux** [comment]
Hahaha... maybe someday I'll feel the same... but I can't justify the cost! ha!
I have a feeling this will suit my addiction just fine for now... xD

**Comment by snakedog116** [comment]
I'm confused, my app seems to respond fairly well with the physical switch (turn it on and the app says the light is on, turn it off and it says the light is off).

Are you saying that you can't get it to respond? What device type are you using for the individual switches?

**Comment by jfrux** [comment]
No, he's just saying he doesn't like the switch to be in the "down" position when the light is technically on, and vica-versa.
Am I right?

**Comment by snakedog116** [comment]
Oh, yea that is kind of annoying... but 3-way switches do that too, even the 'dumb' ones. :)

**Comment by jfrux** [comment]
Right, I think I can deal with it... especially considering how cheap these modules are.
Just can't wait for them to be re-stocked... haven't had the benefit of trying them yet...

Excited xD

**Comment by jfrux** [comment]
Is there a way to use this on 3-way?

**Comment by snakedog116** [comment]
Um.... I'm sure there's a smartapp that could do that... But I've never looked.

As far as hard-wiring it up to be 3-way you are getting into some sketchy wiring that I wouldn't suggest :)

**Comment by jfrux** [comment]
If the switches are wired in this config and I were to use one of these to simply toggle the master switch somehow?

**Comment by jfrux** [comment]
Feel free to blast me if I'm nuts.  I don't know about electrical wiring much other than basics

**Comment by snakedog116** [comment]
Are you talking about toggling the master switch using a smartapp, or a hard wire? I'm not an electrician so I shouldn't speak to hard-wiring it.

My thought would be to do the following:
- Switch 1 is hooked up normally
- Switch 2 only has power, but doesn't have a load.

Here's the scenario:
1. You start with both switches in the off position.
2. Then if you switch 1 on, the light goes on normally.
- It then updates z-wave that the switch is on (this is all part of normal operation)
  1. You would then create a smartapp that watches Switch 1 turn on and then it turns on Switch 2 (which isn't connected to anything).
- (This means that if you turn on Switch 1, both devices go to 'on' position.
  1. Then you would have a SmartApp that does the same thing for the 'off' position.
     **So now you have switch 1 working normally, and switch 2 is following whatever switch 1 does through your smartapps.
     5.Then, the other half of the equation is to use that same smartapp but flip the switches.
- So, if you have both of the light are off, then you switch on 2. The smartapp would see that, and turn on switch 1. and then if you turn off Switch 2, Switch 1 will follow suit and turn off your light.

Should be doable with Rule Machine or something like that... but it would be a lot of work to setup, but if you ask around on the community page there might be a smartapp that has all of that built into 1 so you don't have 4 smartapps running.

Note, if you want to discuss this further, we should do it in SmartThings' community site, not Github Issues page.

**Comment by justintime** [comment]
Quick question, are you both using the included smartapp?  I'm seeing a problem where using that app, when I turn the physical switch on and off quickly (say, 1 second apart), it will toggle the light on and off _twice_.  If I remove the smartapp, but leave the device type in place, things work fine.

**Comment by snakedog116** [comment]
Included SmartApp? I assume you mean yours?
https://github.com/justintime/ST-Monoprice-Dual-Relay-Module/blob/master/smartapps/justintime/dual-relay-adapter.src/dual-relay-adapter.groovy

Yea, I'm using that one.

And yes, Smartthings has a delay while it's talking to the servers, so switching the lights on and off quickly makes it freak out.

Why are you switching lights on an off and on again within a second? There are easier ways to make a strobe light    : p

**Comment by justintime** [comment]
New house, we haven't memorized all the switches yet :)

**Comment by jfrux** [comment]
I'm talking about a currently setup traditional (non-smart) 3 way light switch.
One is a master and one is a slave.
I'd be putting a monoprice module on the master.

When either switch is toggled I'd imagine the power would be turned on which I'd think could theoretically trigger the module.

I'm not familiar with switches either so not sure if this is a valid use or not.

**Comment by snakedog116** [comment]
Oh I see, so you have 2 current switches that are 3-way and you want to replace one with a module and leave the other one as is.

Hmmmm... I don't think this would work how you want it, 3-way switches have extra wires when compared to a 2-way switch.

Having said that, it might work if you put the module in the light box, instead of in the switch box. I'd have to look over the wiring diagram again, but seems to me like that would be your best bet.

**Comment by snakedog116** [comment]
Problem would be in a typical wiring scenario you wouldn't have both constant hot (Black) and constant common (white) at the bulb. You'd have to see if you have that.

Do you have a multimeter? You'd have to see what kinds of wires you have as you'll need to power the relay.

I've copied this thread over to smartthings community, but I can't find you @joshuairl . Please let's continue this there.

**Comment by snakedog116** [comment]
https://community.smartthings.com/t/3-way-switch-with-z-wave-relay/35398

**Comment by justintime** [comment]
Just a note that via #5 I figured out how to stop the "Light Loop" when toggling the switches on and off quickly.  I also added in a feature that will speed up the response time in the device type.
