### ISSUE TITLE
Link to "dual-relay-adapter.groovy" is broken (generates a 404 error)

### ISSUE THREAD

**Issue by Matt-AF** [justintime/ST-Monoprice-Dual-Relay-Module#6]
Hi Justin,

Thank you for the fantastic code!  Just a quick note:  I noticed the link to the "dual-relay-adapter.groovy" wasn't working -- it displayed a 404 error.  I was still able to find your SmartApp code, but I was hoping you might be able to update the hyperlink to this address:

https://github.com/justintime/ST-Monoprice-Dual-Relay-Module/blob/master/smartapps/justintime/dual-relay-adapter.src/dual-relay-adapter.groovy

Thanks,
Matt

**Comment by justintime** [comment]
@Matt-AF good catch!  I've updated the README with the correct link.
